DROP TABLE orders;
DROP TABLE customer;
DROP TABLE car;

CREATE TABLE car (
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY ,
    car_model varchar(255)
);

CREATE TABLE customer (
                     id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY ,
                     first_name varchar(255),
                     last_name varchar(255),
                     phone_number varchar(64) UNIQUE
);

CREATE TABLE orders (
                          id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY ,
                          order_date date not null ,
                          total_price int not null,
                          car_quantity int not null,
                          id_car int references car(id) on delete set null,
                         id_customer int references customer(id) on delete set null
);
